services:
  # web:
  #   build: .
  #   container_name: web_container
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - elastic_todo
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elastic_container
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      - elastic_todo

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana_container
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - "5601:5601"
    networks:
      - elastic_todo

networks:
  elastic_todo: