services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elastic_cont
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.security.enabled: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic_todo
    env_file:
      - .env

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana_cont
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
      ELASTICSEARCH_USERNAME: ${ELASTIC_USER}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - elastic_todo
    depends_on:
      - elastic
    env_file:
      - .env

networks:
  elastic_todo:
    driver: bridge

volumes:
  es_data:
    driver: local